description: # Optional description summary of the module
# A logo for the plugin in SVG format
logo: logo: |
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
            x="0px" y="0px"
            viewBox="0 0 122.88 122.46"
            style="enable-background:new 0 0 122.88 122.46"
            class="mx-auto h-12 w-12 fill-primary"
            xml:space="preserve">
            <style type="text/css">.st0 {
                fill-rule: evenodd;
                clip-rule: evenodd;
            }
            </style>
            <g>
                <path class="st0"
                    d="M69.76,26.16l-7.75,7.75L54.02,42L42.21,53.81l-8.09,7.99l-7.54,7.54c-1.4,1.4-3.68,1.4-5.08,0l-2.95-2.95 c-1.4-1.4-1.4-3.68,0-5.08l43.18-43.18c1.4-1.4,3.68-1.4,5.08,0l2.95,2.95C71.16,22.48,71.16,24.76,69.76,26.16L69.76,26.16z M48.35,26.93L26.93,48.36l-3.18-3.18l21.42-21.42L48.35,26.93L48.35,26.93z M53.12,96.3l7.75-7.75L45.28,72.96 c-2.21-2.21-2.21-5.83,0-8.04l0,0c2.21-2.21,5.83-2.21,8.04,0l15.54,15.54l11.81-11.81L65.13,53.11c-2.21-2.21-2.21-5.83,0-8.04 l0,0c2.21-2.21,5.83-2.21,8.04,0l15.59,15.59l7.54-7.54c1.4-1.4,3.68-1.4,5.08,0l2.95,2.95c1.4,1.4,1.4,3.68,0,5.08l-43.18,43.18 c-1.4,1.4-3.68,1.4-5.08,0l-2.95-2.95C51.72,99.99,51.72,97.7,53.12,96.3L53.12,96.3z M74.48,95.48L95.9,74.06l3.18,3.18 L77.66,98.66L74.48,95.48L74.48,95.48z M63.14,102.33l6.2,6.21c10.79,10.79,20.86,11.28,33.18,1.61l12.31,12.31l8.04-8.04 l-12.41-12.41c9.83-11.93,8.34-23.24-2.11-33.69l-5.6-5.6L63.14,102.33L63.14,102.33z M59.74,20.13l-6.2-6.21 C42.75,3.13,32.67,2.64,20.36,12.31L8.04,0L0,8.04l12.41,12.41c-9.83,11.93-8.34,23.24,2.11,33.69l5.6,5.6L59.74,20.13L59.74,20.13 z"/>
            </g>
        </svg>
menus: # List of menus; support 2 sub-levels (name, type, disabled?, authorities?, subs?, icon?, tooltip?)
    - disabled: false
      name: Administration # Name of menu label
      type: dropDown # Type (link, dropDown, icon, separator, extLink)
      authorities: # Optional list of Role authority /Permission name required to have menu available e.g ROLE_USER
          - ROLE_ADMIN
      subs: # sub-menus
          - route: users # Link invoked when clicked
            name: Users
            icon: keyboard_tab # Optional icon (mat-icon /svg) displayed against the menu item
            type: LINK
webRemotes: # Optional Remote Module Federation Micro-frontends; this is the entry point for Module Federation;
            # any component or module mentioned here should also be exposed in the exposed section of
            # webpack/webpack.common.js
    - remoteEntry: "/across/remoteEntry.js" # URL to load the entry (filename of the webpack ModuleFederationPlugin)
      remoteName: "userMgt" # Entry name. This must match the name field of the webpack ModuleFederationPlugin.
                            # This name has to be unique in the whole application, it's preferable to use uuid to guaranty uniqueness.
                            # Name must start with letter or underscore, and contains only underscore, letters and numbers
      components: # Optional list of Web Component or Angular Component exported by the micro-frontend; componentName and elementName do not go together
                  # React, Vue and other web frameworks should export only Web Components; Angular can export Web Component or native Angular Components
                  # (exposedName, elementName | componentName, position?, routePath?, uuid?, title?, breadcrumb?, authorities?)
          - exposedName: Component # The exported name of the component; matches an 'exposes' key of the webpack ModuleFederationPlugin
            routePath: component # Route path to activate the component
            componentName: Component # Actual component Name. Only applicable for Angular Components
            position: 10 # Optional position in routing order: Note any element that has a routePath may supply this attribute
            name: 318d0123-a2af-462c-a6cc-58ce43b84531 # Optional, if you want the component to be dynamically loadable
          - exposedName: another-omponent
            routePath: another-component
            elementName: AnotherComponent # Web Component /Custom Element, as will be exported by React or Vue, or even Angular
            authorities: # Optional list of Role authority /Permission name required to access the path /component
                - ROLE_DEC
      modules: # Angular Modules exported by the micro-frontend
          - name: UserModule # The exported name of the module; matches an 'exposes' key of the webpack ModuleFederationPlugin
            ngModuleName: UserModule # The Angular module's (@NgModule) name (you should prefer standalone components 😉)
            routePath: users # Route path to activate the module
            title: A page title for the module
            authorities: # Optional list of Role authority /Permission name required to access the path
                - ROLE_DEC
roles: # Optional Roles this module wants installed (name, authority, description?, permissions?)
    - name: Finance Manager
      authority: ROLE_FINANCE_MANAGER # authority must start with ROLE_Roles /Permission
      description: This is a role required by a Finance Manager
      permissions:
        - Edit record
permissions: # Optional list of permission(s) this module wants installed (name, description?)
    - name: Edit record
      description: Data Clerk
